// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

@file:Suppress("NAME_SHADOWING")

package uniffi.connected_core

// Common helper code.
//
// Ideally this would live in a separate .kt file where it can be unittested etc
// in isolation, and perhaps even published as a re-useable package.
//
// However, it's important that the details of how this helper code works (e.g. the
// way that different builtin types are passed across the FFI) exactly match what's
// expected by the Rust code on the other side of the interface. In practice right
// now that means coming from the exact some version of `uniffi` that was used to
// compile the Rust component. The easiest way to ensure this is to bundle the Kotlin
// helpers directly inline like we're doing here.

import com.sun.jna.Library
import com.sun.jna.IntegerType
import com.sun.jna.Native
import com.sun.jna.Pointer
import com.sun.jna.Structure
import com.sun.jna.Callback
import com.sun.jna.ptr.*
import java.nio.ByteBuffer
import java.nio.ByteOrder
import java.nio.CharBuffer
import java.nio.charset.CodingErrorAction
import java.util.concurrent.atomic.AtomicLong
import java.util.concurrent.ConcurrentHashMap

// This is a helper for safely working with byte buffers returned from the Rust code.
// A rust-owned buffer is represented by its capacity, its current length, and a
// pointer to the underlying data.

/**
 * @suppress
 */
@Structure.FieldOrder("capacity", "len", "data")
open class RustBuffer : Structure() {
    // Note: `capacity` and `len` are actually `ULong` values, but JVM only supports signed values.
    // When dealing with these fields, make sure to call `toULong()`.
    @JvmField var capacity: Long = 0
    @JvmField var len: Long = 0
    @JvmField var data: Pointer? = null

    class ByValue: RustBuffer(), Structure.ByValue
    class ByReference: RustBuffer(), Structure.ByReference

   internal fun setValue(other: RustBuffer) {
        capacity = other.capacity
        len = other.len
        data = other.data
    }

    companion object {
        internal fun alloc(size: ULong = 0UL) = uniffiRustCall() { status ->
            // Note: need to convert the size to a `Long` value to make this work with JVM.
            UniffiLib.INSTANCE.ffi_connected_core_rustbuffer_alloc(size.toLong(), status)
        }.also {
            if(it.data == null) {
               throw RuntimeException("RustBuffer.alloc() returned null data pointer (size=${size})")
           }
        }

        internal fun create(capacity: ULong, len: ULong, data: Pointer?): RustBuffer.ByValue {
            var buf = RustBuffer.ByValue()
            buf.capacity = capacity.toLong()
            buf.len = len.toLong()
            buf.data = data
            return buf
        }

        internal fun free(buf: RustBuffer.ByValue) = uniffiRustCall() { status ->
            UniffiLib.INSTANCE.ffi_connected_core_rustbuffer_free(buf, status)
        }
    }

    @Suppress("TooGenericExceptionThrown")
    fun asByteBuffer() =
        this.data?.getByteBuffer(0, this.len.toLong())?.also {
            it.order(ByteOrder.BIG_ENDIAN)
        }
}

/**
 * The equivalent of the `*mut RustBuffer` type.
 * Required for callbacks taking in an out pointer.
 *
 * Size is the sum of all values in the struct.
 *
 * @suppress
 */
class RustBufferByReference : ByReference(16) {
    /**
     * Set the pointed-to `RustBuffer` to the given value.
     */
    fun setValue(value: RustBuffer.ByValue) {
        // NOTE: The offsets are as they are in the C-like struct.
        val pointer = getPointer()
        pointer.setLong(0, value.capacity)
        pointer.setLong(8, value.len)
        pointer.setPointer(16, value.data)
    }

    /**
     * Get a `RustBuffer.ByValue` from this reference.
     */
    fun getValue(): RustBuffer.ByValue {
        val pointer = getPointer()
        val value = RustBuffer.ByValue()
        value.writeField("capacity", pointer.getLong(0))
        value.writeField("len", pointer.getLong(8))
        value.writeField("data", pointer.getLong(16))

        return value
    }
}

// This is a helper for safely passing byte references into the rust code.
// It's not actually used at the moment, because there aren't many things that you
// can take a direct pointer to in the JVM, and if we're going to copy something
// then we might as well copy it into a `RustBuffer`. But it's here for API
// completeness.

@Structure.FieldOrder("len", "data")
internal open class ForeignBytes : Structure() {
    @JvmField var len: Int = 0
    @JvmField var data: Pointer? = null

    class ByValue : ForeignBytes(), Structure.ByValue
}
/**
 * The FfiConverter interface handles converter types to and from the FFI
 *
 * All implementing objects should be public to support external types.  When a
 * type is external we need to import it's FfiConverter.
 *
 * @suppress
 */
public interface FfiConverter<KotlinType, FfiType> {
    // Convert an FFI type to a Kotlin type
    fun lift(value: FfiType): KotlinType

    // Convert an Kotlin type to an FFI type
    fun lower(value: KotlinType): FfiType

    // Read a Kotlin type from a `ByteBuffer`
    fun read(buf: ByteBuffer): KotlinType

    // Calculate bytes to allocate when creating a `RustBuffer`
    //
    // This must return at least as many bytes as the write() function will
    // write. It can return more bytes than needed, for example when writing
    // Strings we can't know the exact bytes needed until we the UTF-8
    // encoding, so we pessimistically allocate the largest size possible (3
    // bytes per codepoint).  Allocating extra bytes is not really a big deal
    // because the `RustBuffer` is short-lived.
    fun allocationSize(value: KotlinType): ULong

    // Write a Kotlin type to a `ByteBuffer`
    fun write(value: KotlinType, buf: ByteBuffer)

    // Lower a value into a `RustBuffer`
    //
    // This method lowers a value into a `RustBuffer` rather than the normal
    // FfiType.  It's used by the callback interface code.  Callback interface
    // returns are always serialized into a `RustBuffer` regardless of their
    // normal FFI type.
    fun lowerIntoRustBuffer(value: KotlinType): RustBuffer.ByValue {
        val rbuf = RustBuffer.alloc(allocationSize(value))
        try {
            val bbuf = rbuf.data!!.getByteBuffer(0, rbuf.capacity).also {
                it.order(ByteOrder.BIG_ENDIAN)
            }
            write(value, bbuf)
            rbuf.writeField("len", bbuf.position().toLong())
            return rbuf
        } catch (e: Throwable) {
            RustBuffer.free(rbuf)
            throw e
        }
    }

    // Lift a value from a `RustBuffer`.
    //
    // This here mostly because of the symmetry with `lowerIntoRustBuffer()`.
    // It's currently only used by the `FfiConverterRustBuffer` class below.
    fun liftFromRustBuffer(rbuf: RustBuffer.ByValue): KotlinType {
        val byteBuf = rbuf.asByteBuffer()!!
        try {
           val item = read(byteBuf)
           if (byteBuf.hasRemaining()) {
               throw RuntimeException("junk remaining in buffer after lifting, something is very wrong!!")
           }
           return item
        } finally {
            RustBuffer.free(rbuf)
        }
    }
}

/**
 * FfiConverter that uses `RustBuffer` as the FfiType
 *
 * @suppress
 */
public interface FfiConverterRustBuffer<KotlinType>: FfiConverter<KotlinType, RustBuffer.ByValue> {
    override fun lift(value: RustBuffer.ByValue) = liftFromRustBuffer(value)
    override fun lower(value: KotlinType) = lowerIntoRustBuffer(value)
}
// A handful of classes and functions to support the generated data structures.
// This would be a good candidate for isolating in its own ffi-support lib.

internal const val UNIFFI_CALL_SUCCESS = 0.toByte()
internal const val UNIFFI_CALL_ERROR = 1.toByte()
internal const val UNIFFI_CALL_UNEXPECTED_ERROR = 2.toByte()

@Structure.FieldOrder("code", "error_buf")
internal open class UniffiRustCallStatus : Structure() {
    @JvmField var code: Byte = 0
    @JvmField var error_buf: RustBuffer.ByValue = RustBuffer.ByValue()

    class ByValue: UniffiRustCallStatus(), Structure.ByValue

    fun isSuccess(): Boolean {
        return code == UNIFFI_CALL_SUCCESS
    }

    fun isError(): Boolean {
        return code == UNIFFI_CALL_ERROR
    }

    fun isPanic(): Boolean {
        return code == UNIFFI_CALL_UNEXPECTED_ERROR
    }

    companion object {
        fun create(code: Byte, errorBuf: RustBuffer.ByValue): UniffiRustCallStatus.ByValue {
            val callStatus = UniffiRustCallStatus.ByValue()
            callStatus.code = code
            callStatus.error_buf = errorBuf
            return callStatus
        }
    }
}

class InternalException(message: String) : kotlin.Exception(message)

/**
 * Each top-level error class has a companion object that can lift the error from the call status's rust buffer
 *
 * @suppress
 */
interface UniffiRustCallStatusErrorHandler<E> {
    fun lift(error_buf: RustBuffer.ByValue): E;
}

// Helpers for calling Rust
// In practice we usually need to be synchronized to call this safely, so it doesn't
// synchronize itself

// Call a rust function that returns a Result<>.  Pass in the Error class companion that corresponds to the Err
private inline fun <U, E: kotlin.Exception> uniffiRustCallWithError(errorHandler: UniffiRustCallStatusErrorHandler<E>, callback: (UniffiRustCallStatus) -> U): U {
    var status = UniffiRustCallStatus()
    val return_value = callback(status)
    uniffiCheckCallStatus(errorHandler, status)
    return return_value
}

// Check UniffiRustCallStatus and throw an error if the call wasn't successful
private fun<E: kotlin.Exception> uniffiCheckCallStatus(errorHandler: UniffiRustCallStatusErrorHandler<E>, status: UniffiRustCallStatus) {
    if (status.isSuccess()) {
        return
    } else if (status.isError()) {
        throw errorHandler.lift(status.error_buf)
    } else if (status.isPanic()) {
        // when the rust code sees a panic, it tries to construct a rustbuffer
        // with the message.  but if that code panics, then it just sends back
        // an empty buffer.
        if (status.error_buf.len > 0) {
            throw InternalException(FfiConverterString.lift(status.error_buf))
        } else {
            throw InternalException("Rust panic")
        }
    } else {
        throw InternalException("Unknown rust call status: $status.code")
    }
}

/**
 * UniffiRustCallStatusErrorHandler implementation for times when we don't expect a CALL_ERROR
 *
 * @suppress
 */
object UniffiNullRustCallStatusErrorHandler: UniffiRustCallStatusErrorHandler<InternalException> {
    override fun lift(error_buf: RustBuffer.ByValue): InternalException {
        RustBuffer.free(error_buf)
        return InternalException("Unexpected CALL_ERROR")
    }
}

// Call a rust function that returns a plain value
private inline fun <U> uniffiRustCall(callback: (UniffiRustCallStatus) -> U): U {
    return uniffiRustCallWithError(UniffiNullRustCallStatusErrorHandler, callback)
}

internal inline fun<T> uniffiTraitInterfaceCall(
    callStatus: UniffiRustCallStatus,
    makeCall: () -> T,
    writeReturn: (T) -> Unit,
) {
    try {
        writeReturn(makeCall())
    } catch(e: kotlin.Exception) {
        callStatus.code = UNIFFI_CALL_UNEXPECTED_ERROR
        callStatus.error_buf = FfiConverterString.lower(e.toString())
    }
}

internal inline fun<T, reified E: Throwable> uniffiTraitInterfaceCallWithError(
    callStatus: UniffiRustCallStatus,
    makeCall: () -> T,
    writeReturn: (T) -> Unit,
    lowerError: (E) -> RustBuffer.ByValue
) {
    try {
        writeReturn(makeCall())
    } catch(e: kotlin.Exception) {
        if (e is E) {
            callStatus.code = UNIFFI_CALL_ERROR
            callStatus.error_buf = lowerError(e)
        } else {
            callStatus.code = UNIFFI_CALL_UNEXPECTED_ERROR
            callStatus.error_buf = FfiConverterString.lower(e.toString())
        }
    }
}
// Map handles to objects
//
// This is used pass an opaque 64-bit handle representing a foreign object to the Rust code.
internal class UniffiHandleMap<T: Any> {
    private val map = ConcurrentHashMap<Long, T>()
    private val counter = java.util.concurrent.atomic.AtomicLong(0)

    val size: Int
        get() = map.size

    // Insert a new object into the handle map and get a handle for it
    fun insert(obj: T): Long {
        val handle = counter.getAndAdd(1)
        map.put(handle, obj)
        return handle
    }

    // Get an object from the handle map
    fun get(handle: Long): T {
        return map.get(handle) ?: throw InternalException("UniffiHandleMap.get: Invalid handle")
    }

    // Remove an entry from the handlemap and get the Kotlin object back
    fun remove(handle: Long): T {
        return map.remove(handle) ?: throw InternalException("UniffiHandleMap: Invalid handle")
    }
}

// Contains loading, initialization code,
// and the FFI Function declarations in a com.sun.jna.Library.
@Synchronized
private fun findLibraryName(componentName: String): String {
    val libOverride = System.getProperty("uniffi.component.$componentName.libraryOverride")
    if (libOverride != null) {
        return libOverride
    }
    return "connected_core"
}

private inline fun <reified Lib : Library> loadIndirect(
    componentName: String
): Lib {
    return Native.load<Lib>(findLibraryName(componentName), Lib::class.java)
}

// Define FFI callback types
internal interface UniffiRustFutureContinuationCallback : com.sun.jna.Callback {
    fun callback(`data`: Long,`pollResult`: Byte,)
}
internal interface UniffiForeignFutureFree : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
}
internal interface UniffiCallbackInterfaceFree : com.sun.jna.Callback {
    fun callback(`handle`: Long,)
}
@Structure.FieldOrder("handle", "free")
internal open class UniffiForeignFuture(
    @JvmField internal var `handle`: Long = 0.toLong(),
    @JvmField internal var `free`: UniffiForeignFutureFree? = null,
) : Structure() {
    class UniffiByValue(
        `handle`: Long = 0.toLong(),
        `free`: UniffiForeignFutureFree? = null,
    ): UniffiForeignFuture(`handle`,`free`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFuture) {
        `handle` = other.`handle`
        `free` = other.`free`
    }

}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU8(
    @JvmField internal var `returnValue`: Byte = 0.toByte(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Byte = 0.toByte(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructU8(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructU8) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU8 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructU8.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI8(
    @JvmField internal var `returnValue`: Byte = 0.toByte(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Byte = 0.toByte(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructI8(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructI8) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI8 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructI8.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU16(
    @JvmField internal var `returnValue`: Short = 0.toShort(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Short = 0.toShort(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructU16(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructU16) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU16 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructU16.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI16(
    @JvmField internal var `returnValue`: Short = 0.toShort(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Short = 0.toShort(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructI16(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructI16) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI16 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructI16.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU32(
    @JvmField internal var `returnValue`: Int = 0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Int = 0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructU32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructU32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructU32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI32(
    @JvmField internal var `returnValue`: Int = 0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Int = 0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructI32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructI32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructI32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructU64(
    @JvmField internal var `returnValue`: Long = 0.toLong(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Long = 0.toLong(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructU64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructU64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteU64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructU64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructI64(
    @JvmField internal var `returnValue`: Long = 0.toLong(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Long = 0.toLong(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructI64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructI64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteI64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructI64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructF32(
    @JvmField internal var `returnValue`: Float = 0.0f,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Float = 0.0f,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructF32(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructF32) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteF32 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructF32.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructF64(
    @JvmField internal var `returnValue`: Double = 0.0,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Double = 0.0,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructF64(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructF64) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteF64 : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructF64.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructPointer(
    @JvmField internal var `returnValue`: Pointer = Pointer.NULL,
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: Pointer = Pointer.NULL,
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructPointer(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructPointer) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompletePointer : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructPointer.UniffiByValue,)
}
@Structure.FieldOrder("returnValue", "callStatus")
internal open class UniffiForeignFutureStructRustBuffer(
    @JvmField internal var `returnValue`: RustBuffer.ByValue = RustBuffer.ByValue(),
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `returnValue`: RustBuffer.ByValue = RustBuffer.ByValue(),
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructRustBuffer(`returnValue`,`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructRustBuffer) {
        `returnValue` = other.`returnValue`
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteRustBuffer : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructRustBuffer.UniffiByValue,)
}
@Structure.FieldOrder("callStatus")
internal open class UniffiForeignFutureStructVoid(
    @JvmField internal var `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
) : Structure() {
    class UniffiByValue(
        `callStatus`: UniffiRustCallStatus.ByValue = UniffiRustCallStatus.ByValue(),
    ): UniffiForeignFutureStructVoid(`callStatus`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiForeignFutureStructVoid) {
        `callStatus` = other.`callStatus`
    }

}
internal interface UniffiForeignFutureCompleteVoid : com.sun.jna.Callback {
    fun callback(`callbackData`: Long,`result`: UniffiForeignFutureStructVoid.UniffiByValue,)
}
internal interface UniffiCallbackInterfaceClipboardCallbackMethod0 : com.sun.jna.Callback {
    fun callback(`uniffiHandle`: Long,`text`: RustBuffer.ByValue,`fromDevice`: RustBuffer.ByValue,`uniffiOutReturn`: Pointer,uniffiCallStatus: UniffiRustCallStatus,)
}
internal interface UniffiCallbackInterfaceClipboardCallbackMethod1 : com.sun.jna.Callback {
    fun callback(`uniffiHandle`: Long,`success`: Byte,`errorMsg`: RustBuffer.ByValue,`uniffiOutReturn`: Pointer,uniffiCallStatus: UniffiRustCallStatus,)
}
internal interface UniffiCallbackInterfaceDiscoveryCallbackMethod0 : com.sun.jna.Callback {
    fun callback(`uniffiHandle`: Long,`device`: RustBuffer.ByValue,`uniffiOutReturn`: Pointer,uniffiCallStatus: UniffiRustCallStatus,)
}
internal interface UniffiCallbackInterfaceDiscoveryCallbackMethod1 : com.sun.jna.Callback {
    fun callback(`uniffiHandle`: Long,`deviceId`: RustBuffer.ByValue,`uniffiOutReturn`: Pointer,uniffiCallStatus: UniffiRustCallStatus,)
}
internal interface UniffiCallbackInterfaceDiscoveryCallbackMethod2 : com.sun.jna.Callback {
    fun callback(`uniffiHandle`: Long,`errorMsg`: RustBuffer.ByValue,`uniffiOutReturn`: Pointer,uniffiCallStatus: UniffiRustCallStatus,)
}
internal interface UniffiCallbackInterfaceFileTransferCallbackMethod0 : com.sun.jna.Callback {
    fun callback(`uniffiHandle`: Long,`filename`: RustBuffer.ByValue,`totalSize`: Long,`uniffiOutReturn`: Pointer,uniffiCallStatus: UniffiRustCallStatus,)
}
internal interface UniffiCallbackInterfaceFileTransferCallbackMethod1 : com.sun.jna.Callback {
    fun callback(`uniffiHandle`: Long,`bytesTransferred`: Long,`totalSize`: Long,`uniffiOutReturn`: Pointer,uniffiCallStatus: UniffiRustCallStatus,)
}
internal interface UniffiCallbackInterfaceFileTransferCallbackMethod2 : com.sun.jna.Callback {
    fun callback(`uniffiHandle`: Long,`filename`: RustBuffer.ByValue,`totalSize`: Long,`uniffiOutReturn`: Pointer,uniffiCallStatus: UniffiRustCallStatus,)
}
internal interface UniffiCallbackInterfaceFileTransferCallbackMethod3 : com.sun.jna.Callback {
    fun callback(`uniffiHandle`: Long,`errorMsg`: RustBuffer.ByValue,`uniffiOutReturn`: Pointer,uniffiCallStatus: UniffiRustCallStatus,)
}
internal interface UniffiCallbackInterfaceFileTransferCallbackMethod4 : com.sun.jna.Callback {
    fun callback(`uniffiHandle`: Long,`uniffiOutReturn`: Pointer,uniffiCallStatus: UniffiRustCallStatus,)
}
@Structure.FieldOrder("onClipboardReceived", "onClipboardSent", "uniffiFree")
internal open class UniffiVTableCallbackInterfaceClipboardCallback(
    @JvmField internal var `onClipboardReceived`: UniffiCallbackInterfaceClipboardCallbackMethod0? = null,
    @JvmField internal var `onClipboardSent`: UniffiCallbackInterfaceClipboardCallbackMethod1? = null,
    @JvmField internal var `uniffiFree`: UniffiCallbackInterfaceFree? = null,
) : Structure() {
    class UniffiByValue(
        `onClipboardReceived`: UniffiCallbackInterfaceClipboardCallbackMethod0? = null,
        `onClipboardSent`: UniffiCallbackInterfaceClipboardCallbackMethod1? = null,
        `uniffiFree`: UniffiCallbackInterfaceFree? = null,
    ): UniffiVTableCallbackInterfaceClipboardCallback(`onClipboardReceived`,`onClipboardSent`,`uniffiFree`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiVTableCallbackInterfaceClipboardCallback) {
        `onClipboardReceived` = other.`onClipboardReceived`
        `onClipboardSent` = other.`onClipboardSent`
        `uniffiFree` = other.`uniffiFree`
    }

}
@Structure.FieldOrder("onDeviceFound", "onDeviceLost", "onError", "uniffiFree")
internal open class UniffiVTableCallbackInterfaceDiscoveryCallback(
    @JvmField internal var `onDeviceFound`: UniffiCallbackInterfaceDiscoveryCallbackMethod0? = null,
    @JvmField internal var `onDeviceLost`: UniffiCallbackInterfaceDiscoveryCallbackMethod1? = null,
    @JvmField internal var `onError`: UniffiCallbackInterfaceDiscoveryCallbackMethod2? = null,
    @JvmField internal var `uniffiFree`: UniffiCallbackInterfaceFree? = null,
) : Structure() {
    class UniffiByValue(
        `onDeviceFound`: UniffiCallbackInterfaceDiscoveryCallbackMethod0? = null,
        `onDeviceLost`: UniffiCallbackInterfaceDiscoveryCallbackMethod1? = null,
        `onError`: UniffiCallbackInterfaceDiscoveryCallbackMethod2? = null,
        `uniffiFree`: UniffiCallbackInterfaceFree? = null,
    ): UniffiVTableCallbackInterfaceDiscoveryCallback(`onDeviceFound`,`onDeviceLost`,`onError`,`uniffiFree`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiVTableCallbackInterfaceDiscoveryCallback) {
        `onDeviceFound` = other.`onDeviceFound`
        `onDeviceLost` = other.`onDeviceLost`
        `onError` = other.`onError`
        `uniffiFree` = other.`uniffiFree`
    }

}
@Structure.FieldOrder("onTransferStarting", "onTransferProgress", "onTransferCompleted", "onTransferFailed", "onTransferCancelled", "uniffiFree")
internal open class UniffiVTableCallbackInterfaceFileTransferCallback(
    @JvmField internal var `onTransferStarting`: UniffiCallbackInterfaceFileTransferCallbackMethod0? = null,
    @JvmField internal var `onTransferProgress`: UniffiCallbackInterfaceFileTransferCallbackMethod1? = null,
    @JvmField internal var `onTransferCompleted`: UniffiCallbackInterfaceFileTransferCallbackMethod2? = null,
    @JvmField internal var `onTransferFailed`: UniffiCallbackInterfaceFileTransferCallbackMethod3? = null,
    @JvmField internal var `onTransferCancelled`: UniffiCallbackInterfaceFileTransferCallbackMethod4? = null,
    @JvmField internal var `uniffiFree`: UniffiCallbackInterfaceFree? = null,
) : Structure() {
    class UniffiByValue(
        `onTransferStarting`: UniffiCallbackInterfaceFileTransferCallbackMethod0? = null,
        `onTransferProgress`: UniffiCallbackInterfaceFileTransferCallbackMethod1? = null,
        `onTransferCompleted`: UniffiCallbackInterfaceFileTransferCallbackMethod2? = null,
        `onTransferFailed`: UniffiCallbackInterfaceFileTransferCallbackMethod3? = null,
        `onTransferCancelled`: UniffiCallbackInterfaceFileTransferCallbackMethod4? = null,
        `uniffiFree`: UniffiCallbackInterfaceFree? = null,
    ): UniffiVTableCallbackInterfaceFileTransferCallback(`onTransferStarting`,`onTransferProgress`,`onTransferCompleted`,`onTransferFailed`,`onTransferCancelled`,`uniffiFree`,), Structure.ByValue

   internal fun uniffiSetValue(other: UniffiVTableCallbackInterfaceFileTransferCallback) {
        `onTransferStarting` = other.`onTransferStarting`
        `onTransferProgress` = other.`onTransferProgress`
        `onTransferCompleted` = other.`onTransferCompleted`
        `onTransferFailed` = other.`onTransferFailed`
        `onTransferCancelled` = other.`onTransferCancelled`
        `uniffiFree` = other.`uniffiFree`
    }

}

































































































// For large crates we prevent `MethodTooLargeException` (see #2340)
// N.B. the name of the extension is very misleading, since it is 
// rather `InterfaceTooLargeException`, caused by too many methods 
// in the interface for large crates.
//
// By splitting the otherwise huge interface into two parts
// * UniffiLib 
// * IntegrityCheckingUniffiLib (this)
// we allow for ~2x as many methods in the UniffiLib interface.
// 
// The `ffi_uniffi_contract_version` method and all checksum methods are put 
// into `IntegrityCheckingUniffiLib` and these methods are called only once,
// when the library is loaded.
internal interface IntegrityCheckingUniffiLib : Library {
    // Integrity check functions only
    fun uniffi_connected_core_checksum_func_clear_discovered_devices(
): Short
fun uniffi_connected_core_checksum_func_get_discovered_devices(
): Short
fun uniffi_connected_core_checksum_func_get_local_device(
): Short
fun uniffi_connected_core_checksum_func_initialize(
): Short
fun uniffi_connected_core_checksum_func_initialize_with_ip(
): Short
fun uniffi_connected_core_checksum_func_register_clipboard_receiver(
): Short
fun uniffi_connected_core_checksum_func_send_clipboard(
): Short
fun uniffi_connected_core_checksum_func_send_file(
): Short
fun uniffi_connected_core_checksum_func_send_ping(
): Short
fun uniffi_connected_core_checksum_func_shutdown(
): Short
fun uniffi_connected_core_checksum_func_start_discovery(
): Short
fun uniffi_connected_core_checksum_func_start_file_receiver(
): Short
fun uniffi_connected_core_checksum_func_stop_discovery(
): Short
fun uniffi_connected_core_checksum_method_clipboardcallback_on_clipboard_received(
): Short
fun uniffi_connected_core_checksum_method_clipboardcallback_on_clipboard_sent(
): Short
fun uniffi_connected_core_checksum_method_discoverycallback_on_device_found(
): Short
fun uniffi_connected_core_checksum_method_discoverycallback_on_device_lost(
): Short
fun uniffi_connected_core_checksum_method_discoverycallback_on_error(
): Short
fun uniffi_connected_core_checksum_method_filetransfercallback_on_transfer_starting(
): Short
fun uniffi_connected_core_checksum_method_filetransfercallback_on_transfer_progress(
): Short
fun uniffi_connected_core_checksum_method_filetransfercallback_on_transfer_completed(
): Short
fun uniffi_connected_core_checksum_method_filetransfercallback_on_transfer_failed(
): Short
fun uniffi_connected_core_checksum_method_filetransfercallback_on_transfer_cancelled(
): Short
fun ffi_connected_core_uniffi_contract_version(
): Int

}

// A JNA Library to expose the extern-C FFI definitions.
// This is an implementation detail which will be called internally by the public API.
internal interface UniffiLib : Library {
    companion object {
        internal val INSTANCE: UniffiLib by lazy {
            val componentName = "connected_core"
            // For large crates we prevent `MethodTooLargeException` (see #2340)
            // N.B. the name of the extension is very misleading, since it is 
            // rather `InterfaceTooLargeException`, caused by too many methods 
            // in the interface for large crates.
            //
            // By splitting the otherwise huge interface into two parts
            // * UniffiLib (this)
            // * IntegrityCheckingUniffiLib
            // And all checksum methods are put into `IntegrityCheckingUniffiLib`
            // we allow for ~2x as many methods in the UniffiLib interface.
            // 
            // Thus we first load the library with `loadIndirect` as `IntegrityCheckingUniffiLib`
            // so that we can (optionally!) call `uniffiCheckApiChecksums`...
            loadIndirect<IntegrityCheckingUniffiLib>(componentName)
                .also { lib: IntegrityCheckingUniffiLib ->
                    uniffiCheckContractApiVersion(lib)
                    uniffiCheckApiChecksums(lib)
                }
            // ... and then we load the library as `UniffiLib`
            // N.B. we cannot use `loadIndirect` once and then try to cast it to `UniffiLib`
            // => results in `java.lang.ClassCastException: com.sun.proxy.$Proxy cannot be cast to ...`
            // error. So we must call `loadIndirect` twice. For crates large enough
            // to trigger this issue, the performance impact is negligible, running on
            // a macOS M1 machine the `loadIndirect` call takes ~50ms.
            val lib = loadIndirect<UniffiLib>(componentName)
            // No need to check the contract version and checksums, since 
            // we already did that with `IntegrityCheckingUniffiLib` above.
            uniffiCallbackInterfaceClipboardCallback.register(lib)
            uniffiCallbackInterfaceDiscoveryCallback.register(lib)
            uniffiCallbackInterfaceFileTransferCallback.register(lib)
            // Loading of library with integrity check done.
            lib
        }
        
    }

    // FFI functions
    fun uniffi_connected_core_fn_init_callback_vtable_clipboardcallback(`vtable`: UniffiVTableCallbackInterfaceClipboardCallback,
): Unit
fun uniffi_connected_core_fn_init_callback_vtable_discoverycallback(`vtable`: UniffiVTableCallbackInterfaceDiscoveryCallback,
): Unit
fun uniffi_connected_core_fn_init_callback_vtable_filetransfercallback(`vtable`: UniffiVTableCallbackInterfaceFileTransferCallback,
): Unit
fun uniffi_connected_core_fn_func_clear_discovered_devices(uniffi_out_err: UniffiRustCallStatus, 
): Unit
fun uniffi_connected_core_fn_func_get_discovered_devices(uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun uniffi_connected_core_fn_func_get_local_device(uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun uniffi_connected_core_fn_func_initialize(`deviceName`: RustBuffer.ByValue,`deviceType`: RustBuffer.ByValue,`bindPort`: Short,uniffi_out_err: UniffiRustCallStatus, 
): Unit
fun uniffi_connected_core_fn_func_initialize_with_ip(`deviceName`: RustBuffer.ByValue,`deviceType`: RustBuffer.ByValue,`bindPort`: Short,`ipAddress`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): Unit
fun uniffi_connected_core_fn_func_register_clipboard_receiver(`callback`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Unit
fun uniffi_connected_core_fn_func_send_clipboard(`targetIp`: RustBuffer.ByValue,`targetPort`: Short,`text`: RustBuffer.ByValue,`callback`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Unit
fun uniffi_connected_core_fn_func_send_file(`targetIp`: RustBuffer.ByValue,`targetPort`: Short,`filePath`: RustBuffer.ByValue,`callback`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Unit
fun uniffi_connected_core_fn_func_send_ping(`targetIp`: RustBuffer.ByValue,`targetPort`: Short,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun uniffi_connected_core_fn_func_shutdown(uniffi_out_err: UniffiRustCallStatus, 
): Unit
fun uniffi_connected_core_fn_func_start_discovery(`callback`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Unit
fun uniffi_connected_core_fn_func_start_file_receiver(`saveDir`: RustBuffer.ByValue,`callback`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Unit
fun uniffi_connected_core_fn_func_stop_discovery(uniffi_out_err: UniffiRustCallStatus, 
): Unit
fun ffi_connected_core_rustbuffer_alloc(`size`: Long,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun ffi_connected_core_rustbuffer_from_bytes(`bytes`: ForeignBytes.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun ffi_connected_core_rustbuffer_free(`buf`: RustBuffer.ByValue,uniffi_out_err: UniffiRustCallStatus, 
): Unit
fun ffi_connected_core_rustbuffer_reserve(`buf`: RustBuffer.ByValue,`additional`: Long,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun ffi_connected_core_rust_future_poll_u8(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
fun ffi_connected_core_rust_future_cancel_u8(`handle`: Long,
): Unit
fun ffi_connected_core_rust_future_free_u8(`handle`: Long,
): Unit
fun ffi_connected_core_rust_future_complete_u8(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Byte
fun ffi_connected_core_rust_future_poll_i8(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
fun ffi_connected_core_rust_future_cancel_i8(`handle`: Long,
): Unit
fun ffi_connected_core_rust_future_free_i8(`handle`: Long,
): Unit
fun ffi_connected_core_rust_future_complete_i8(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Byte
fun ffi_connected_core_rust_future_poll_u16(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
fun ffi_connected_core_rust_future_cancel_u16(`handle`: Long,
): Unit
fun ffi_connected_core_rust_future_free_u16(`handle`: Long,
): Unit
fun ffi_connected_core_rust_future_complete_u16(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Short
fun ffi_connected_core_rust_future_poll_i16(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
fun ffi_connected_core_rust_future_cancel_i16(`handle`: Long,
): Unit
fun ffi_connected_core_rust_future_free_i16(`handle`: Long,
): Unit
fun ffi_connected_core_rust_future_complete_i16(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Short
fun ffi_connected_core_rust_future_poll_u32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
fun ffi_connected_core_rust_future_cancel_u32(`handle`: Long,
): Unit
fun ffi_connected_core_rust_future_free_u32(`handle`: Long,
): Unit
fun ffi_connected_core_rust_future_complete_u32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Int
fun ffi_connected_core_rust_future_poll_i32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
fun ffi_connected_core_rust_future_cancel_i32(`handle`: Long,
): Unit
fun ffi_connected_core_rust_future_free_i32(`handle`: Long,
): Unit
fun ffi_connected_core_rust_future_complete_i32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Int
fun ffi_connected_core_rust_future_poll_u64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
fun ffi_connected_core_rust_future_cancel_u64(`handle`: Long,
): Unit
fun ffi_connected_core_rust_future_free_u64(`handle`: Long,
): Unit
fun ffi_connected_core_rust_future_complete_u64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Long
fun ffi_connected_core_rust_future_poll_i64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
fun ffi_connected_core_rust_future_cancel_i64(`handle`: Long,
): Unit
fun ffi_connected_core_rust_future_free_i64(`handle`: Long,
): Unit
fun ffi_connected_core_rust_future_complete_i64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Long
fun ffi_connected_core_rust_future_poll_f32(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
fun ffi_connected_core_rust_future_cancel_f32(`handle`: Long,
): Unit
fun ffi_connected_core_rust_future_free_f32(`handle`: Long,
): Unit
fun ffi_connected_core_rust_future_complete_f32(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Float
fun ffi_connected_core_rust_future_poll_f64(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
fun ffi_connected_core_rust_future_cancel_f64(`handle`: Long,
): Unit
fun ffi_connected_core_rust_future_free_f64(`handle`: Long,
): Unit
fun ffi_connected_core_rust_future_complete_f64(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Double
fun ffi_connected_core_rust_future_poll_pointer(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
fun ffi_connected_core_rust_future_cancel_pointer(`handle`: Long,
): Unit
fun ffi_connected_core_rust_future_free_pointer(`handle`: Long,
): Unit
fun ffi_connected_core_rust_future_complete_pointer(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Pointer
fun ffi_connected_core_rust_future_poll_rust_buffer(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
fun ffi_connected_core_rust_future_cancel_rust_buffer(`handle`: Long,
): Unit
fun ffi_connected_core_rust_future_free_rust_buffer(`handle`: Long,
): Unit
fun ffi_connected_core_rust_future_complete_rust_buffer(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): RustBuffer.ByValue
fun ffi_connected_core_rust_future_poll_void(`handle`: Long,`callback`: UniffiRustFutureContinuationCallback,`callbackData`: Long,
): Unit
fun ffi_connected_core_rust_future_cancel_void(`handle`: Long,
): Unit
fun ffi_connected_core_rust_future_free_void(`handle`: Long,
): Unit
fun ffi_connected_core_rust_future_complete_void(`handle`: Long,uniffi_out_err: UniffiRustCallStatus, 
): Unit

}

private fun uniffiCheckContractApiVersion(lib: IntegrityCheckingUniffiLib) {
    // Get the bindings contract version from our ComponentInterface
    val bindings_contract_version = 29
    // Get the scaffolding contract version by calling the into the dylib
    val scaffolding_contract_version = lib.ffi_connected_core_uniffi_contract_version()
    if (bindings_contract_version != scaffolding_contract_version) {
        throw RuntimeException("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    }
}
@Suppress("UNUSED_PARAMETER")
private fun uniffiCheckApiChecksums(lib: IntegrityCheckingUniffiLib) {
    if (lib.uniffi_connected_core_checksum_func_clear_discovered_devices() != 1658.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_connected_core_checksum_func_get_discovered_devices() != 43746.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_connected_core_checksum_func_get_local_device() != 45042.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_connected_core_checksum_func_initialize() != 28512.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_connected_core_checksum_func_initialize_with_ip() != 60880.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_connected_core_checksum_func_register_clipboard_receiver() != 13447.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_connected_core_checksum_func_send_clipboard() != 61828.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_connected_core_checksum_func_send_file() != 36936.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_connected_core_checksum_func_send_ping() != 45751.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_connected_core_checksum_func_shutdown() != 25738.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_connected_core_checksum_func_start_discovery() != 3575.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_connected_core_checksum_func_start_file_receiver() != 46928.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_connected_core_checksum_func_stop_discovery() != 61531.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_connected_core_checksum_method_clipboardcallback_on_clipboard_received() != 38339.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_connected_core_checksum_method_clipboardcallback_on_clipboard_sent() != 52786.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_connected_core_checksum_method_discoverycallback_on_device_found() != 7929.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_connected_core_checksum_method_discoverycallback_on_device_lost() != 3156.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_connected_core_checksum_method_discoverycallback_on_error() != 19382.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_connected_core_checksum_method_filetransfercallback_on_transfer_starting() != 43243.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_connected_core_checksum_method_filetransfercallback_on_transfer_progress() != 42139.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_connected_core_checksum_method_filetransfercallback_on_transfer_completed() != 26430.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_connected_core_checksum_method_filetransfercallback_on_transfer_failed() != 58667.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
    if (lib.uniffi_connected_core_checksum_method_filetransfercallback_on_transfer_cancelled() != 30994.toShort()) {
        throw RuntimeException("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

/**
 * @suppress
 */
public fun uniffiEnsureInitialized() {
    UniffiLib.INSTANCE
}

// Async support

// Public interface members begin here.


// Interface implemented by anything that can contain an object reference.
//
// Such types expose a `destroy()` method that must be called to cleanly
// dispose of the contained objects. Failure to call this method may result
// in memory leaks.
//
// The easiest way to ensure this method is called is to use the `.use`
// helper method to execute a block and destroy the object at the end.
interface Disposable {
    fun destroy()
    companion object {
        fun destroy(vararg args: Any?) {
            for (arg in args) {
                when (arg) {
                    is Disposable -> arg.destroy()
                    is ArrayList<*> -> {
                        for (idx in arg.indices) {
                            val element = arg[idx]
                            if (element is Disposable) {
                                element.destroy()
                            }
                        }
                    }
                    is Map<*, *> -> {
                        for (element in arg.values) {
                            if (element is Disposable) {
                                element.destroy()
                            }
                        }
                    }
                    is Iterable<*> -> {
                        for (element in arg) {
                            if (element is Disposable) {
                                element.destroy()
                            }
                        }
                    }
                }
            }
        }
    }
}

/**
 * @suppress
 */
inline fun <T : Disposable?, R> T.use(block: (T) -> R) =
    try {
        block(this)
    } finally {
        try {
            // N.B. our implementation is on the nullable type `Disposable?`.
            this?.destroy()
        } catch (e: Throwable) {
            // swallow
        }
    }

/** 
 * Used to instantiate an interface without an actual pointer, for fakes in tests, mostly.
 *
 * @suppress
 * */
object NoPointer// Magic number for the Rust proxy to call using the same mechanism as every other method,
// to free the callback once it's dropped by Rust.
internal const val IDX_CALLBACK_FREE = 0
// Callback return codes
internal const val UNIFFI_CALLBACK_SUCCESS = 0
internal const val UNIFFI_CALLBACK_ERROR = 1
internal const val UNIFFI_CALLBACK_UNEXPECTED_ERROR = 2

/**
 * @suppress
 */
public abstract class FfiConverterCallbackInterface<CallbackInterface: Any>: FfiConverter<CallbackInterface, Long> {
    internal val handleMap = UniffiHandleMap<CallbackInterface>()

    internal fun drop(handle: Long) {
        handleMap.remove(handle)
    }

    override fun lift(value: Long): CallbackInterface {
        return handleMap.get(value)
    }

    override fun read(buf: ByteBuffer) = lift(buf.getLong())

    override fun lower(value: CallbackInterface) = handleMap.insert(value)

    override fun allocationSize(value: CallbackInterface) = 8UL

    override fun write(value: CallbackInterface, buf: ByteBuffer) {
        buf.putLong(lower(value))
    }
}

/**
 * @suppress
 */
public object FfiConverterUShort: FfiConverter<UShort, Short> {
    override fun lift(value: Short): UShort {
        return value.toUShort()
    }

    override fun read(buf: ByteBuffer): UShort {
        return lift(buf.getShort())
    }

    override fun lower(value: UShort): Short {
        return value.toShort()
    }

    override fun allocationSize(value: UShort) = 2UL

    override fun write(value: UShort, buf: ByteBuffer) {
        buf.putShort(value.toShort())
    }
}

/**
 * @suppress
 */
public object FfiConverterULong: FfiConverter<ULong, Long> {
    override fun lift(value: Long): ULong {
        return value.toULong()
    }

    override fun read(buf: ByteBuffer): ULong {
        return lift(buf.getLong())
    }

    override fun lower(value: ULong): Long {
        return value.toLong()
    }

    override fun allocationSize(value: ULong) = 8UL

    override fun write(value: ULong, buf: ByteBuffer) {
        buf.putLong(value.toLong())
    }
}

/**
 * @suppress
 */
public object FfiConverterBoolean: FfiConverter<Boolean, Byte> {
    override fun lift(value: Byte): Boolean {
        return value.toInt() != 0
    }

    override fun read(buf: ByteBuffer): Boolean {
        return lift(buf.get())
    }

    override fun lower(value: Boolean): Byte {
        return if (value) 1.toByte() else 0.toByte()
    }

    override fun allocationSize(value: Boolean) = 1UL

    override fun write(value: Boolean, buf: ByteBuffer) {
        buf.put(lower(value))
    }
}

/**
 * @suppress
 */
public object FfiConverterString: FfiConverter<String, RustBuffer.ByValue> {
    // Note: we don't inherit from FfiConverterRustBuffer, because we use a
    // special encoding when lowering/lifting.  We can use `RustBuffer.len` to
    // store our length and avoid writing it out to the buffer.
    override fun lift(value: RustBuffer.ByValue): String {
        try {
            val byteArr = ByteArray(value.len.toInt())
            value.asByteBuffer()!!.get(byteArr)
            return byteArr.toString(Charsets.UTF_8)
        } finally {
            RustBuffer.free(value)
        }
    }

    override fun read(buf: ByteBuffer): String {
        val len = buf.getInt()
        val byteArr = ByteArray(len)
        buf.get(byteArr)
        return byteArr.toString(Charsets.UTF_8)
    }

    fun toUtf8(value: String): ByteBuffer {
        // Make sure we don't have invalid UTF-16, check for lone surrogates.
        return Charsets.UTF_8.newEncoder().run {
            onMalformedInput(CodingErrorAction.REPORT)
            encode(CharBuffer.wrap(value))
        }
    }

    override fun lower(value: String): RustBuffer.ByValue {
        val byteBuf = toUtf8(value)
        // Ideally we'd pass these bytes to `ffi_bytebuffer_from_bytes`, but doing so would require us
        // to copy them into a JNA `Memory`. So we might as well directly copy them into a `RustBuffer`.
        val rbuf = RustBuffer.alloc(byteBuf.limit().toULong())
        rbuf.asByteBuffer()!!.put(byteBuf)
        return rbuf
    }

    // We aren't sure exactly how many bytes our string will be once it's UTF-8
    // encoded.  Allocate 3 bytes per UTF-16 code unit which will always be
    // enough.
    override fun allocationSize(value: String): ULong {
        val sizeForLength = 4UL
        val sizeForString = value.length.toULong() * 3UL
        return sizeForLength + sizeForString
    }

    override fun write(value: String, buf: ByteBuffer) {
        val byteBuf = toUtf8(value)
        buf.putInt(byteBuf.limit())
        buf.put(byteBuf)
    }
}



data class Device (
    var `id`: kotlin.String, 
    var `name`: kotlin.String, 
    var `ip`: kotlin.String, 
    var `port`: kotlin.UShort, 
    var `deviceType`: DeviceType
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeDevice: FfiConverterRustBuffer<Device> {
    override fun read(buf: ByteBuffer): Device {
        return Device(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterUShort.read(buf),
            FfiConverterTypeDeviceType.read(buf),
        )
    }

    override fun allocationSize(value: Device) = (
            FfiConverterString.allocationSize(value.`id`) +
            FfiConverterString.allocationSize(value.`name`) +
            FfiConverterString.allocationSize(value.`ip`) +
            FfiConverterUShort.allocationSize(value.`port`) +
            FfiConverterTypeDeviceType.allocationSize(value.`deviceType`)
    )

    override fun write(value: Device, buf: ByteBuffer) {
            FfiConverterString.write(value.`id`, buf)
            FfiConverterString.write(value.`name`, buf)
            FfiConverterString.write(value.`ip`, buf)
            FfiConverterUShort.write(value.`port`, buf)
            FfiConverterTypeDeviceType.write(value.`deviceType`, buf)
    }
}



data class DiscoveredDevice (
    var `id`: kotlin.String, 
    var `name`: kotlin.String, 
    var `ip`: kotlin.String, 
    var `port`: kotlin.UShort, 
    var `deviceType`: kotlin.String
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeDiscoveredDevice: FfiConverterRustBuffer<DiscoveredDevice> {
    override fun read(buf: ByteBuffer): DiscoveredDevice {
        return DiscoveredDevice(
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterString.read(buf),
            FfiConverterUShort.read(buf),
            FfiConverterString.read(buf),
        )
    }

    override fun allocationSize(value: DiscoveredDevice) = (
            FfiConverterString.allocationSize(value.`id`) +
            FfiConverterString.allocationSize(value.`name`) +
            FfiConverterString.allocationSize(value.`ip`) +
            FfiConverterUShort.allocationSize(value.`port`) +
            FfiConverterString.allocationSize(value.`deviceType`)
    )

    override fun write(value: DiscoveredDevice, buf: ByteBuffer) {
            FfiConverterString.write(value.`id`, buf)
            FfiConverterString.write(value.`name`, buf)
            FfiConverterString.write(value.`ip`, buf)
            FfiConverterUShort.write(value.`port`, buf)
            FfiConverterString.write(value.`deviceType`, buf)
    }
}



data class FileTransferInfo (
    var `filename`: kotlin.String, 
    var `size`: kotlin.ULong, 
    var `mimeType`: kotlin.String?
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypeFileTransferInfo: FfiConverterRustBuffer<FileTransferInfo> {
    override fun read(buf: ByteBuffer): FileTransferInfo {
        return FileTransferInfo(
            FfiConverterString.read(buf),
            FfiConverterULong.read(buf),
            FfiConverterOptionalString.read(buf),
        )
    }

    override fun allocationSize(value: FileTransferInfo) = (
            FfiConverterString.allocationSize(value.`filename`) +
            FfiConverterULong.allocationSize(value.`size`) +
            FfiConverterOptionalString.allocationSize(value.`mimeType`)
    )

    override fun write(value: FileTransferInfo, buf: ByteBuffer) {
            FfiConverterString.write(value.`filename`, buf)
            FfiConverterULong.write(value.`size`, buf)
            FfiConverterOptionalString.write(value.`mimeType`, buf)
    }
}



data class PingResult (
    var `success`: kotlin.Boolean, 
    var `rttMs`: kotlin.ULong, 
    var `errorMessage`: kotlin.String?
) {
    
    companion object
}

/**
 * @suppress
 */
public object FfiConverterTypePingResult: FfiConverterRustBuffer<PingResult> {
    override fun read(buf: ByteBuffer): PingResult {
        return PingResult(
            FfiConverterBoolean.read(buf),
            FfiConverterULong.read(buf),
            FfiConverterOptionalString.read(buf),
        )
    }

    override fun allocationSize(value: PingResult) = (
            FfiConverterBoolean.allocationSize(value.`success`) +
            FfiConverterULong.allocationSize(value.`rttMs`) +
            FfiConverterOptionalString.allocationSize(value.`errorMessage`)
    )

    override fun write(value: PingResult, buf: ByteBuffer) {
            FfiConverterBoolean.write(value.`success`, buf)
            FfiConverterULong.write(value.`rttMs`, buf)
            FfiConverterOptionalString.write(value.`errorMessage`, buf)
    }
}





sealed class ConnectedFfiException: kotlin.Exception() {
    
    class InitializationException(
        
        val `msg`: kotlin.String
        ) : ConnectedFfiException() {
        override val message
            get() = "msg=${ `msg` }"
    }
    
    class DiscoveryException(
        
        val `msg`: kotlin.String
        ) : ConnectedFfiException() {
        override val message
            get() = "msg=${ `msg` }"
    }
    
    class ConnectionException(
        
        val `msg`: kotlin.String
        ) : ConnectedFfiException() {
        override val message
            get() = "msg=${ `msg` }"
    }
    
    class NotInitialized(
        ) : ConnectedFfiException() {
        override val message
            get() = ""
    }
    
    class InvalidArgument(
        
        val `msg`: kotlin.String
        ) : ConnectedFfiException() {
        override val message
            get() = "msg=${ `msg` }"
    }
    

    companion object ErrorHandler : UniffiRustCallStatusErrorHandler<ConnectedFfiException> {
        override fun lift(error_buf: RustBuffer.ByValue): ConnectedFfiException = FfiConverterTypeConnectedFfiError.lift(error_buf)
    }

    
}

/**
 * @suppress
 */
public object FfiConverterTypeConnectedFfiError : FfiConverterRustBuffer<ConnectedFfiException> {
    override fun read(buf: ByteBuffer): ConnectedFfiException {
        

        return when(buf.getInt()) {
            1 -> ConnectedFfiException.InitializationException(
                FfiConverterString.read(buf),
                )
            2 -> ConnectedFfiException.DiscoveryException(
                FfiConverterString.read(buf),
                )
            3 -> ConnectedFfiException.ConnectionException(
                FfiConverterString.read(buf),
                )
            4 -> ConnectedFfiException.NotInitialized()
            5 -> ConnectedFfiException.InvalidArgument(
                FfiConverterString.read(buf),
                )
            else -> throw RuntimeException("invalid error enum value, something is very wrong!!")
        }
    }

    override fun allocationSize(value: ConnectedFfiException): ULong {
        return when(value) {
            is ConnectedFfiException.InitializationException -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
                + FfiConverterString.allocationSize(value.`msg`)
            )
            is ConnectedFfiException.DiscoveryException -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
                + FfiConverterString.allocationSize(value.`msg`)
            )
            is ConnectedFfiException.ConnectionException -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
                + FfiConverterString.allocationSize(value.`msg`)
            )
            is ConnectedFfiException.NotInitialized -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
            )
            is ConnectedFfiException.InvalidArgument -> (
                // Add the size for the Int that specifies the variant plus the size needed for all fields
                4UL
                + FfiConverterString.allocationSize(value.`msg`)
            )
        }
    }

    override fun write(value: ConnectedFfiException, buf: ByteBuffer) {
        when(value) {
            is ConnectedFfiException.InitializationException -> {
                buf.putInt(1)
                FfiConverterString.write(value.`msg`, buf)
                Unit
            }
            is ConnectedFfiException.DiscoveryException -> {
                buf.putInt(2)
                FfiConverterString.write(value.`msg`, buf)
                Unit
            }
            is ConnectedFfiException.ConnectionException -> {
                buf.putInt(3)
                FfiConverterString.write(value.`msg`, buf)
                Unit
            }
            is ConnectedFfiException.NotInitialized -> {
                buf.putInt(4)
                Unit
            }
            is ConnectedFfiException.InvalidArgument -> {
                buf.putInt(5)
                FfiConverterString.write(value.`msg`, buf)
                Unit
            }
        }.let { /* this makes the `when` an expression, which ensures it is exhaustive */ }
    }

}




enum class DeviceType {
    
    ANDROID,
    LINUX,
    WINDOWS,
    MAC_OS,
    UNKNOWN;
    companion object
}


/**
 * @suppress
 */
public object FfiConverterTypeDeviceType: FfiConverterRustBuffer<DeviceType> {
    override fun read(buf: ByteBuffer) = try {
        DeviceType.values()[buf.getInt() - 1]
    } catch (e: IndexOutOfBoundsException) {
        throw RuntimeException("invalid enum value, something is very wrong!!", e)
    }

    override fun allocationSize(value: DeviceType) = 4UL

    override fun write(value: DeviceType, buf: ByteBuffer) {
        buf.putInt(value.ordinal + 1)
    }
}







public interface ClipboardCallback {
    
    fun `onClipboardReceived`(`text`: kotlin.String, `fromDevice`: kotlin.String)
    
    fun `onClipboardSent`(`success`: kotlin.Boolean, `errorMsg`: kotlin.String?)
    
    companion object
}



// Put the implementation in an object so we don't pollute the top-level namespace
internal object uniffiCallbackInterfaceClipboardCallback {
    internal object `onClipboardReceived`: UniffiCallbackInterfaceClipboardCallbackMethod0 {
        override fun callback(`uniffiHandle`: Long,`text`: RustBuffer.ByValue,`fromDevice`: RustBuffer.ByValue,`uniffiOutReturn`: Pointer,uniffiCallStatus: UniffiRustCallStatus,) {
            val uniffiObj = FfiConverterTypeClipboardCallback.handleMap.get(uniffiHandle)
            val makeCall = { ->
                uniffiObj.`onClipboardReceived`(
                    FfiConverterString.lift(`text`),
                    FfiConverterString.lift(`fromDevice`),
                )
            }
            val writeReturn = { _: Unit -> Unit }
            uniffiTraitInterfaceCall(uniffiCallStatus, makeCall, writeReturn)
        }
    }
    internal object `onClipboardSent`: UniffiCallbackInterfaceClipboardCallbackMethod1 {
        override fun callback(`uniffiHandle`: Long,`success`: Byte,`errorMsg`: RustBuffer.ByValue,`uniffiOutReturn`: Pointer,uniffiCallStatus: UniffiRustCallStatus,) {
            val uniffiObj = FfiConverterTypeClipboardCallback.handleMap.get(uniffiHandle)
            val makeCall = { ->
                uniffiObj.`onClipboardSent`(
                    FfiConverterBoolean.lift(`success`),
                    FfiConverterOptionalString.lift(`errorMsg`),
                )
            }
            val writeReturn = { _: Unit -> Unit }
            uniffiTraitInterfaceCall(uniffiCallStatus, makeCall, writeReturn)
        }
    }

    internal object uniffiFree: UniffiCallbackInterfaceFree {
        override fun callback(handle: Long) {
            FfiConverterTypeClipboardCallback.handleMap.remove(handle)
        }
    }

    internal var vtable = UniffiVTableCallbackInterfaceClipboardCallback.UniffiByValue(
        `onClipboardReceived`,
        `onClipboardSent`,
        uniffiFree,
    )

    // Registers the foreign callback with the Rust side.
    // This method is generated for each callback interface.
    internal fun register(lib: UniffiLib) {
        lib.uniffi_connected_core_fn_init_callback_vtable_clipboardcallback(vtable)
    }
}

/**
 * The ffiConverter which transforms the Callbacks in to handles to pass to Rust.
 *
 * @suppress
 */
public object FfiConverterTypeClipboardCallback: FfiConverterCallbackInterface<ClipboardCallback>()





public interface DiscoveryCallback {
    
    fun `onDeviceFound`(`device`: DiscoveredDevice)
    
    fun `onDeviceLost`(`deviceId`: kotlin.String)
    
    fun `onError`(`errorMsg`: kotlin.String)
    
    companion object
}



// Put the implementation in an object so we don't pollute the top-level namespace
internal object uniffiCallbackInterfaceDiscoveryCallback {
    internal object `onDeviceFound`: UniffiCallbackInterfaceDiscoveryCallbackMethod0 {
        override fun callback(`uniffiHandle`: Long,`device`: RustBuffer.ByValue,`uniffiOutReturn`: Pointer,uniffiCallStatus: UniffiRustCallStatus,) {
            val uniffiObj = FfiConverterTypeDiscoveryCallback.handleMap.get(uniffiHandle)
            val makeCall = { ->
                uniffiObj.`onDeviceFound`(
                    FfiConverterTypeDiscoveredDevice.lift(`device`),
                )
            }
            val writeReturn = { _: Unit -> Unit }
            uniffiTraitInterfaceCall(uniffiCallStatus, makeCall, writeReturn)
        }
    }
    internal object `onDeviceLost`: UniffiCallbackInterfaceDiscoveryCallbackMethod1 {
        override fun callback(`uniffiHandle`: Long,`deviceId`: RustBuffer.ByValue,`uniffiOutReturn`: Pointer,uniffiCallStatus: UniffiRustCallStatus,) {
            val uniffiObj = FfiConverterTypeDiscoveryCallback.handleMap.get(uniffiHandle)
            val makeCall = { ->
                uniffiObj.`onDeviceLost`(
                    FfiConverterString.lift(`deviceId`),
                )
            }
            val writeReturn = { _: Unit -> Unit }
            uniffiTraitInterfaceCall(uniffiCallStatus, makeCall, writeReturn)
        }
    }
    internal object `onError`: UniffiCallbackInterfaceDiscoveryCallbackMethod2 {
        override fun callback(`uniffiHandle`: Long,`errorMsg`: RustBuffer.ByValue,`uniffiOutReturn`: Pointer,uniffiCallStatus: UniffiRustCallStatus,) {
            val uniffiObj = FfiConverterTypeDiscoveryCallback.handleMap.get(uniffiHandle)
            val makeCall = { ->
                uniffiObj.`onError`(
                    FfiConverterString.lift(`errorMsg`),
                )
            }
            val writeReturn = { _: Unit -> Unit }
            uniffiTraitInterfaceCall(uniffiCallStatus, makeCall, writeReturn)
        }
    }

    internal object uniffiFree: UniffiCallbackInterfaceFree {
        override fun callback(handle: Long) {
            FfiConverterTypeDiscoveryCallback.handleMap.remove(handle)
        }
    }

    internal var vtable = UniffiVTableCallbackInterfaceDiscoveryCallback.UniffiByValue(
        `onDeviceFound`,
        `onDeviceLost`,
        `onError`,
        uniffiFree,
    )

    // Registers the foreign callback with the Rust side.
    // This method is generated for each callback interface.
    internal fun register(lib: UniffiLib) {
        lib.uniffi_connected_core_fn_init_callback_vtable_discoverycallback(vtable)
    }
}

/**
 * The ffiConverter which transforms the Callbacks in to handles to pass to Rust.
 *
 * @suppress
 */
public object FfiConverterTypeDiscoveryCallback: FfiConverterCallbackInterface<DiscoveryCallback>()





public interface FileTransferCallback {
    
    fun `onTransferStarting`(`filename`: kotlin.String, `totalSize`: kotlin.ULong)
    
    fun `onTransferProgress`(`bytesTransferred`: kotlin.ULong, `totalSize`: kotlin.ULong)
    
    fun `onTransferCompleted`(`filename`: kotlin.String, `totalSize`: kotlin.ULong)
    
    fun `onTransferFailed`(`errorMsg`: kotlin.String)
    
    fun `onTransferCancelled`()
    
    companion object
}



// Put the implementation in an object so we don't pollute the top-level namespace
internal object uniffiCallbackInterfaceFileTransferCallback {
    internal object `onTransferStarting`: UniffiCallbackInterfaceFileTransferCallbackMethod0 {
        override fun callback(`uniffiHandle`: Long,`filename`: RustBuffer.ByValue,`totalSize`: Long,`uniffiOutReturn`: Pointer,uniffiCallStatus: UniffiRustCallStatus,) {
            val uniffiObj = FfiConverterTypeFileTransferCallback.handleMap.get(uniffiHandle)
            val makeCall = { ->
                uniffiObj.`onTransferStarting`(
                    FfiConverterString.lift(`filename`),
                    FfiConverterULong.lift(`totalSize`),
                )
            }
            val writeReturn = { _: Unit -> Unit }
            uniffiTraitInterfaceCall(uniffiCallStatus, makeCall, writeReturn)
        }
    }
    internal object `onTransferProgress`: UniffiCallbackInterfaceFileTransferCallbackMethod1 {
        override fun callback(`uniffiHandle`: Long,`bytesTransferred`: Long,`totalSize`: Long,`uniffiOutReturn`: Pointer,uniffiCallStatus: UniffiRustCallStatus,) {
            val uniffiObj = FfiConverterTypeFileTransferCallback.handleMap.get(uniffiHandle)
            val makeCall = { ->
                uniffiObj.`onTransferProgress`(
                    FfiConverterULong.lift(`bytesTransferred`),
                    FfiConverterULong.lift(`totalSize`),
                )
            }
            val writeReturn = { _: Unit -> Unit }
            uniffiTraitInterfaceCall(uniffiCallStatus, makeCall, writeReturn)
        }
    }
    internal object `onTransferCompleted`: UniffiCallbackInterfaceFileTransferCallbackMethod2 {
        override fun callback(`uniffiHandle`: Long,`filename`: RustBuffer.ByValue,`totalSize`: Long,`uniffiOutReturn`: Pointer,uniffiCallStatus: UniffiRustCallStatus,) {
            val uniffiObj = FfiConverterTypeFileTransferCallback.handleMap.get(uniffiHandle)
            val makeCall = { ->
                uniffiObj.`onTransferCompleted`(
                    FfiConverterString.lift(`filename`),
                    FfiConverterULong.lift(`totalSize`),
                )
            }
            val writeReturn = { _: Unit -> Unit }
            uniffiTraitInterfaceCall(uniffiCallStatus, makeCall, writeReturn)
        }
    }
    internal object `onTransferFailed`: UniffiCallbackInterfaceFileTransferCallbackMethod3 {
        override fun callback(`uniffiHandle`: Long,`errorMsg`: RustBuffer.ByValue,`uniffiOutReturn`: Pointer,uniffiCallStatus: UniffiRustCallStatus,) {
            val uniffiObj = FfiConverterTypeFileTransferCallback.handleMap.get(uniffiHandle)
            val makeCall = { ->
                uniffiObj.`onTransferFailed`(
                    FfiConverterString.lift(`errorMsg`),
                )
            }
            val writeReturn = { _: Unit -> Unit }
            uniffiTraitInterfaceCall(uniffiCallStatus, makeCall, writeReturn)
        }
    }
    internal object `onTransferCancelled`: UniffiCallbackInterfaceFileTransferCallbackMethod4 {
        override fun callback(`uniffiHandle`: Long,`uniffiOutReturn`: Pointer,uniffiCallStatus: UniffiRustCallStatus,) {
            val uniffiObj = FfiConverterTypeFileTransferCallback.handleMap.get(uniffiHandle)
            val makeCall = { ->
                uniffiObj.`onTransferCancelled`(
                )
            }
            val writeReturn = { _: Unit -> Unit }
            uniffiTraitInterfaceCall(uniffiCallStatus, makeCall, writeReturn)
        }
    }

    internal object uniffiFree: UniffiCallbackInterfaceFree {
        override fun callback(handle: Long) {
            FfiConverterTypeFileTransferCallback.handleMap.remove(handle)
        }
    }

    internal var vtable = UniffiVTableCallbackInterfaceFileTransferCallback.UniffiByValue(
        `onTransferStarting`,
        `onTransferProgress`,
        `onTransferCompleted`,
        `onTransferFailed`,
        `onTransferCancelled`,
        uniffiFree,
    )

    // Registers the foreign callback with the Rust side.
    // This method is generated for each callback interface.
    internal fun register(lib: UniffiLib) {
        lib.uniffi_connected_core_fn_init_callback_vtable_filetransfercallback(vtable)
    }
}

/**
 * The ffiConverter which transforms the Callbacks in to handles to pass to Rust.
 *
 * @suppress
 */
public object FfiConverterTypeFileTransferCallback: FfiConverterCallbackInterface<FileTransferCallback>()




/**
 * @suppress
 */
public object FfiConverterOptionalString: FfiConverterRustBuffer<kotlin.String?> {
    override fun read(buf: ByteBuffer): kotlin.String? {
        if (buf.get().toInt() == 0) {
            return null
        }
        return FfiConverterString.read(buf)
    }

    override fun allocationSize(value: kotlin.String?): ULong {
        if (value == null) {
            return 1UL
        } else {
            return 1UL + FfiConverterString.allocationSize(value)
        }
    }

    override fun write(value: kotlin.String?, buf: ByteBuffer) {
        if (value == null) {
            buf.put(0)
        } else {
            buf.put(1)
            FfiConverterString.write(value, buf)
        }
    }
}




/**
 * @suppress
 */
public object FfiConverterSequenceTypeDiscoveredDevice: FfiConverterRustBuffer<List<DiscoveredDevice>> {
    override fun read(buf: ByteBuffer): List<DiscoveredDevice> {
        val len = buf.getInt()
        return List<DiscoveredDevice>(len) {
            FfiConverterTypeDiscoveredDevice.read(buf)
        }
    }

    override fun allocationSize(value: List<DiscoveredDevice>): ULong {
        val sizeForLength = 4UL
        val sizeForItems = value.map { FfiConverterTypeDiscoveredDevice.allocationSize(it) }.sum()
        return sizeForLength + sizeForItems
    }

    override fun write(value: List<DiscoveredDevice>, buf: ByteBuffer) {
        buf.putInt(value.size)
        value.iterator().forEach {
            FfiConverterTypeDiscoveredDevice.write(it, buf)
        }
    }
}
    @Throws(ConnectedFfiException::class) fun `clearDiscoveredDevices`()
        = 
    uniffiRustCallWithError(ConnectedFfiException) { _status ->
    UniffiLib.INSTANCE.uniffi_connected_core_fn_func_clear_discovered_devices(
        _status)
}
    
    

    @Throws(ConnectedFfiException::class) fun `getDiscoveredDevices`(): List<DiscoveredDevice> {
            return FfiConverterSequenceTypeDiscoveredDevice.lift(
    uniffiRustCallWithError(ConnectedFfiException) { _status ->
    UniffiLib.INSTANCE.uniffi_connected_core_fn_func_get_discovered_devices(
        _status)
}
    )
    }
    

    @Throws(ConnectedFfiException::class) fun `getLocalDevice`(): DiscoveredDevice {
            return FfiConverterTypeDiscoveredDevice.lift(
    uniffiRustCallWithError(ConnectedFfiException) { _status ->
    UniffiLib.INSTANCE.uniffi_connected_core_fn_func_get_local_device(
        _status)
}
    )
    }
    

    @Throws(ConnectedFfiException::class) fun `initialize`(`deviceName`: kotlin.String, `deviceType`: kotlin.String, `bindPort`: kotlin.UShort)
        = 
    uniffiRustCallWithError(ConnectedFfiException) { _status ->
    UniffiLib.INSTANCE.uniffi_connected_core_fn_func_initialize(
        FfiConverterString.lower(`deviceName`),FfiConverterString.lower(`deviceType`),FfiConverterUShort.lower(`bindPort`),_status)
}
    
    

    @Throws(ConnectedFfiException::class) fun `initializeWithIp`(`deviceName`: kotlin.String, `deviceType`: kotlin.String, `bindPort`: kotlin.UShort, `ipAddress`: kotlin.String)
        = 
    uniffiRustCallWithError(ConnectedFfiException) { _status ->
    UniffiLib.INSTANCE.uniffi_connected_core_fn_func_initialize_with_ip(
        FfiConverterString.lower(`deviceName`),FfiConverterString.lower(`deviceType`),FfiConverterUShort.lower(`bindPort`),FfiConverterString.lower(`ipAddress`),_status)
}
    
    
 fun `registerClipboardReceiver`(`callback`: ClipboardCallback)
        = 
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_connected_core_fn_func_register_clipboard_receiver(
        FfiConverterTypeClipboardCallback.lower(`callback`),_status)
}
    
    

    @Throws(ConnectedFfiException::class) fun `sendClipboard`(`targetIp`: kotlin.String, `targetPort`: kotlin.UShort, `text`: kotlin.String, `callback`: ClipboardCallback)
        = 
    uniffiRustCallWithError(ConnectedFfiException) { _status ->
    UniffiLib.INSTANCE.uniffi_connected_core_fn_func_send_clipboard(
        FfiConverterString.lower(`targetIp`),FfiConverterUShort.lower(`targetPort`),FfiConverterString.lower(`text`),FfiConverterTypeClipboardCallback.lower(`callback`),_status)
}
    
    

    @Throws(ConnectedFfiException::class) fun `sendFile`(`targetIp`: kotlin.String, `targetPort`: kotlin.UShort, `filePath`: kotlin.String, `callback`: FileTransferCallback)
        = 
    uniffiRustCallWithError(ConnectedFfiException) { _status ->
    UniffiLib.INSTANCE.uniffi_connected_core_fn_func_send_file(
        FfiConverterString.lower(`targetIp`),FfiConverterUShort.lower(`targetPort`),FfiConverterString.lower(`filePath`),FfiConverterTypeFileTransferCallback.lower(`callback`),_status)
}
    
    
 fun `sendPing`(`targetIp`: kotlin.String, `targetPort`: kotlin.UShort): PingResult {
            return FfiConverterTypePingResult.lift(
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_connected_core_fn_func_send_ping(
        FfiConverterString.lower(`targetIp`),FfiConverterUShort.lower(`targetPort`),_status)
}
    )
    }
    
 fun `shutdown`()
        = 
    uniffiRustCall() { _status ->
    UniffiLib.INSTANCE.uniffi_connected_core_fn_func_shutdown(
        _status)
}
    
    

    @Throws(ConnectedFfiException::class) fun `startDiscovery`(`callback`: DiscoveryCallback)
        = 
    uniffiRustCallWithError(ConnectedFfiException) { _status ->
    UniffiLib.INSTANCE.uniffi_connected_core_fn_func_start_discovery(
        FfiConverterTypeDiscoveryCallback.lower(`callback`),_status)
}
    
    

    @Throws(ConnectedFfiException::class) fun `startFileReceiver`(`saveDir`: kotlin.String, `callback`: FileTransferCallback)
        = 
    uniffiRustCallWithError(ConnectedFfiException) { _status ->
    UniffiLib.INSTANCE.uniffi_connected_core_fn_func_start_file_receiver(
        FfiConverterString.lower(`saveDir`),FfiConverterTypeFileTransferCallback.lower(`callback`),_status)
}
    
    

    @Throws(ConnectedFfiException::class) fun `stopDiscovery`()
        = 
    uniffiRustCallWithError(ConnectedFfiException) { _status ->
    UniffiLib.INSTANCE.uniffi_connected_core_fn_func_stop_discovery(
        _status)
}
    
    


