use serde::{Deserialize, Serialize};
use std::net::IpAddr;

/// Represents the type/platform of a connected device.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum DeviceType {
    Android,
    Linux,
    Windows,
    /// Reserved for future macOS support. Not currently implemented but kept
    /// for forward compatibility with the protocol and stored device data.
    MacOS,
    Unknown,
}

impl DeviceType {
    pub fn as_str(&self) -> &'static str {
        match self {
            DeviceType::Android => "android",
            DeviceType::Linux => "linux",
            DeviceType::Windows => "windows",
            DeviceType::MacOS => "macos",
            DeviceType::Unknown => "unknown",
        }
    }
}

impl std::str::FromStr for DeviceType {
    type Err = ();

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s.to_lowercase().as_str() {
            "android" => Ok(DeviceType::Android),
            "linux" => Ok(DeviceType::Linux),
            "windows" => Ok(DeviceType::Windows),
            "macos" => Ok(DeviceType::MacOS),
            _ => Ok(DeviceType::Unknown),
        }
    }
}

/// Represents a network peer that Can connect or has connected to the current node.
///
/// This struct holds all of the necessary network and identity information required
/// to establish, authenticate, and manage an active `QUIC` connection session.
///
/// The `id` is typically expected to be a unique cryptographic fingerprint (like a TLS cert hash)
/// or a universally unique identifier generated by the peer upon first installation.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct Device {
    /// A unique identifier for the device (typically a TLS fingerprint or UUID).
    pub id: String,
    /// A human-readable display name for the device, synced from the peer's settings.
    pub name: String,
    /// The IP address of the device (kept as a string for easy Serialization).
    pub ip: String,
    /// The discovery or transport port the device is listening on.
    pub port: u16,
    /// The operating system the device is running.
    pub device_type: DeviceType,
}

impl Device {
    /// Creates a new `Device` instance from the given network and identity parameters.
    pub fn new(id: String, name: String, ip: IpAddr, port: u16, device_type: DeviceType) -> Self {
        Self {
            id,
            name,
            ip: ip.to_string(),
            port,
            device_type,
        }
    }

    pub fn ip_addr(&self) -> Option<IpAddr> {
        match self.ip.parse() {
            Ok(addr) => Some(addr),
            Err(e) => {
                tracing::warn!(
                    "Failed to parse IP address '{}' for device {}: {}",
                    self.ip,
                    self.id,
                    e
                );
                None
            }
        }
    }
}
